### ISSUE TITLE
No basic auth credentials error on push

### ISSUE THREAD

**Issue by bryannaegele** [codeship-library/aws-ecr-dockercfg-generator#4]
I've been having some difficulty getting this workflow going. I am able to build and push images to AWS ECR when logging in and using the AWS CLI locally but keep getting an auth related error when running with Jet.

Is there a need to do further credential setup that I'm missing here?

``` bash
jet steps --tag="master" --push=true --debug=true
{StepStarted=step_name:"web_build"}

.... image build....

{BuildImageStdout=image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname" service_name:"web"}: Successfully built 8a9d4d126c15
{BuildImageFinished=image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname" service_name:"web"}
{ContainerRunStdout=step_name:"web_build" service_name:"web"}: web built
{StepFinished=step_name:"web_build" type:STEP_FINISHED_TYPE_SUCCESS}
{StepStarted=step_name:"web_staging_push_step"}
{ContainerRunStdout=step_name:"web_staging_push_step" service_name:"aws_dockercfg"}: Logging into AWS ECR
{ContainerRunStdout=step_name:"web_staging_push_step" service_name:"aws_dockercfg"}: WARNING: login credentials saved in /root/.docker/config.json
{ContainerRunStdout=step_name:"web_staging_push_step" service_name:"aws_dockercfg"}: Login Succeeded
{ContainerRunStdout=step_name:"web_staging_push_step" service_name:"aws_dockercfg"}: Writing Docker creds to /tmp/credentials/codeship-dockercfg247539887/codeship-dockercfg491271746
{PushImageStarted=step_name:"web_staging_push_step" service_name:"web" image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname"}
{PushImageStdout=step_name:"web_staging_push_step" service_name:"web" image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname"}: The push refers to a repository [xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname]
{PushImageStdout=step_name:"web_staging_push_step" service_name:"web" image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname"}: Preparing
{PushImageStdout=step_name:"web_staging_push_step" service_name:"web" image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname"}: Preparing

... preparing logs continue for a while...

{PushImageStdout=step_name:"web_staging_push_step" service_name:"web" image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname"}: Retrying in 5 seconds
{PushImageStdout=step_name:"web_staging_push_step" service_name:"web" image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname"}: Retrying in 5 seconds
{PushImageStdout=step_name:"web_staging_push_step" service_name:"web" image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname"}: Retrying in 5 seconds
{PushImageStdout=step_name:"web_staging_push_step" service_name:"web" image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname"}: Waiting
{PushImageStdout=step_name:"web_staging_push_step" service_name:"web" image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname"}: Waiting
{PushImageStdout=step_name:"web_staging_push_step" service_name:"web" image_name:"xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname"}: Waiting

.... waiting and retries in the log for a while....

{StepFinished=step_name:"web_staging_push_step" type:STEP_FINISHED_TYPE_ERROR}
Image Push error for image xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname:latest, no basic auth credentials
```

services

``` yaml
web:
  build:
    image: xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname
    dockerfile_path: ./Dockerfile
  environment:
    NODE_PATH: /dist/node_modules
  cached: true

aws_dockercfg:
  image: codeship/aws-ecr-dockercfg-generator
  add_docker: true
  encrypted_env_file: aws.env.encrypted
```

steps

``` yaml
- type: serial
  steps:
    - name: web_build
      service: web
      command: echo web built
    - name: web_staging_push_step
      service: web
      type: push
      tag: master
      image_name: xxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/integritystl/projectname
      registry: https://xxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/
      dockercfg_service: aws_dockercfg
```

repo permissions

``` json
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "push_pull",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::xxxxxxxxxxx:root"
            },
            "Action": [
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability",
                "ecr:PutImage",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload"
            ]
        }
    ]
}
```
